---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: killercoda-com-web
  namespace: monitoring
  labels:
    prometheus: main
spec:
  jobName: killercoda-web
  interval: 15s
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring:9115
  targets:
    staticConfig:
      static:
        - https://killercoda.com
