---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: le-http01-staging
  namespace: monitoring
spec:
  acme:
    email: security@svestor.link
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: le-http01-staging-tls
    solvers:
      - http01:
          ingress:
            ingressClassName: external-nginx
