---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: flask-app-secrets
  namespace: flask-ns
spec:
  provider: aws
  parameters:
    region: us-east-1
    usePodIdentity: "true"
    preferredAddressType: "ipv4" # (ipv4 | ipv6)
    objects: |
      - objectName: "dev/flask-app-secret-v1"
        objectType: "secretsmanager"
        jmesPath:
            - path: "username"
              objectAlias: "flask_app_username"
            - path: "password"
              objectAlias: "flask_app_password"
  secretObjects:
    - secretName: flask-app-secrets
      type: Opaque
      data:
        - objectName: "flask_app_username"
          key: "flask_app_username_key"
        - objectName: "flask_app_password"
          key: "flask_app_password_key"
