---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: flask-ns
spec:
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      serviceAccountName: flask-app-sa
      containers:
        - name: flask-app
          image: svestor/flask-session-app:v1
          ports:
            - name: app
              containerPort: 8080
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 200m
          env:
            - name: FLASK_APP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: flask-app-secrets
                  key: "flask_app_username_key"
            - name: FLASK_APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flask-app-secrets
                  key: "flask_app_password_key" 
          volumeMounts:
            - name: flask-app-secrets
              mountPath: /mnt/secrets-store
              readOnly: true
      volumes:
      - name: flask-app-secrets
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "flask-app-secrets"
