---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-storage-class-exp
parameters:
  fsType: ext4
  type: gp3
  # encrypted: "true"
  # kmsKeyId: arn:aws:kms:us-east-1:123456789012:key/abcd1234-abcd-5678-abcd-efghijklmnop
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
