---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flask-app
  namespace: flask-ns
spec:
  serviceName: flask-app
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: svestor/flask-session-app:v1
          ports:
            - name: app
              containerPort: 8080
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 200m
          volumeMounts:
            - name: data
              mountPath: /data
      terminationGracePeriodSeconds: 30          
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: gp3-storage-class-exp
        resources:
          requests:
            storage: 5Gi
