{
 "title": "CPUs Usage",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total,container_label_io_kubernetes_pod_namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{container_label_io_kubernetes_pod_namespace=\"$namespace\"},container_label_io_kubernetes_pod_name)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{container_label_io_kubernetes_pod_namespace=\"$namespace\", container_label_io_kubernetes_pod_name=\"$pod\"},container_label_io_kubernetes_container_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage in Cores with Requests and Limits",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    container_cpu_usage_seconds_total\n    {\n       container_label_io_kubernetes_pod_name=~\"$pod\",\n       container_label_io_kubernetes_container_name=~\"$container\",\n       container_label_io_kubernetes_pod_namespace=~\"$namespace\",\n       image!=\"\",\n       container_label_io_cri_containerd_kind=\"container\"\n    }[1m]\n  )\n)\nby (container_label_io_kubernetes_pod_name,container_label_io_kubernetes_container_name)",
     "legendFormat": "{{container_label_io_kubernetes_container_name}} in {{container_label_io_kubernetes_pod_name}}"
    },
    {
     "expr": "avg(\n  kube_pod_container_resource_limits\n  {\n      exported_pod=~\"$pod\",\n      exported_namespace=~\"$namespace\",\n      exported_container=~\"$container\",\n      unit=\"core\"\n  }\n)",
     "legendFormat": "Limit"
    },
    {
     "expr": "avg(\n  kube_pod_container_resource_requests\n  {\n      exported_pod=~\"$pod\",\n      exported_namespace=~\"$namespace\",\n      exported_container=~\"$container\",\n      unit=\"core\"\n  }\n)",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(\n  container_cpu_cfs_throttled_seconds_total\n  {\n    container_label_io_kubernetes_pod_namespace=~\"$namespace\",\n    image!=\"\",\n    container_label_io_cri_containerd_kind=\"container\"\n  }[1m])",
     "legendFormat": "{{container_label_io_kubernetes_container_name}} in {{container_label_io_kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage in % of the Limit",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{\n    container_label_io_kubernetes_pod_namespace=~\"$namespace\",\n    image!=\"\",\n    container_label_io_cri_containerd_kind=\"container\"\n  }[1m])\n)\nby (container_label_io_kubernetes_pod_name, container_label_io_kubernetes_container_name)\n/\nsum(\n  container_spec_cpu_quota{\n    container_label_io_kubernetes_pod_namespace=~\"$namespace\",\n    image!=\"\",\n    container_label_io_cri_containerd_kind=\"container\"\n  }\n  /\n  container_spec_cpu_period{\n    container_label_io_kubernetes_pod_namespace=~\"$namespace\",\n    image!=\"\",\n    container_label_io_cri_containerd_kind=\"container\"\n  }\n)\nby (container_label_io_kubernetes_pod_name, container_label_io_kubernetes_container_name)",
     "legendFormat": "{{container_label_io_kubernetes_container_name}} in {{container_label_io_kubernetes_pod_name}}"
    }
   ]
  }
 ]
}