{
 "title": "Prometheus Volumes",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kubelet_volume_stats_capacity_bytes,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Persistent Volume Usage per Namespace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{namespace=~\"$namespace\"} / kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Persistent Volume Inodes Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_inodes_used / kubelet_volume_stats_inodes",
     "legendFormat": "{{ persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Persistent Volume Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}