{
 "title": "Prometheus Volumes",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kubelet_volume_stats_capacity_bytes,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Persistent Volume Status by Phase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase=\"Pending\"} == 1) by (phase,persistentvolume)",
     "legendFormat": "{{phase}}-{{persistentvolume}}"
    },
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase=\"Available\"} == 1) by (phase,persistentvolume)",
     "legendFormat": "{{phase}}-{{persistentvolume}}"
    },
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase=\"Bound\"} == 1) by (phase,persistentvolume)",
     "legendFormat": "{{phase}}-{{persistentvolume}}"
    },
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase=\"Released\"} == 1) by (phase,persistentvolume)",
     "legendFormat": "{{phase}}-{{persistentvolume}}"
    },
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase=\"Failed\"} == 1) by (phase,persistentvolume)",
     "legendFormat": "{{phase}}-{{persistentvolume}}"
    }
   ]
  },
  {
   "title": "Persistent Volume Claim Status by Phase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{phase=\"Pending\"} == 1) by (phase,persistentvolumeclaim,exported_namespace)",
     "legendFormat": "{{phase}}-{{persistentvolumeclaim}}-{{exported_namespace}}"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{phase=\"Lost\"} == 1) by (phase,persistentvolumeclaim,exported_namespace)",
     "legendFormat": "{{phase}}-{{persistentvolumeclaim}}-{{exported_namespace}}"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{phase=\"Bound\"} == 1) by (phase,persistentvolumeclaim,exported_namespace)\n",
     "legendFormat": "{{phase}}-{{persistentvolumeclaim}}-{{exported_namespace}}"
    }
   ]
  },
  {
   "title": "Persistent Volume Usage per Namespace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{namespace=~\"$namespace\"} / kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Persistent Volume Inodes Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_inodes_used / kubelet_volume_stats_inodes",
     "legendFormat": "{{ persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Persistent Volume Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}