---
# Source: cert-manager/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cert-manager
  namespace: monitoring
  labels:
    app: cert-manager
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/component: "controller"
    app.kubernetes.io/version: "v1.17.2"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: cert-manager-v1.17.2
    prometheus: main
spec:
  jobLabel: cert-manager
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
        - cainjector
        - cert-manager
        - webhook
      - key: app.kubernetes.io/instance
        operator: In
        values:
        - cert-manager
      - key: app.kubernetes.io/component
        operator: In
        values:
        - cainjector
        - controller
        - webhook
  namespaceSelector:
    matchNames:
      - cert-manager
  endpoints:
  - targetPort: 9402
    path: /metrics
    interval: 60s
    scrapeTimeout: 30s
    honorLabels: false
