---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: http01-prod
spec:
  acme:
    email: security@svestor.link
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: http01-prod-cluster-issuer
    solvers:
      - http01:
          ingress:
            ingressClassName: external-nginx
