---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-viewer-rolebinding
roleRef:
  kind: ClusterRole
  name: cluster-viewer-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    name: viewers
    apiGroup: rbac.authorization.k8s.io
