---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-1
  namespace: test-ns
spec:
  containers:
    - name: test-1
      image: busybox
      command: ["/bin/sh"]
      args:
        [
          "-c",
          "while true; do echo $(date -u) >> /data/out1.txt; sleep 5; done",
        ]
      volumeMounts:
        - name: persistent-efs-storage
          mountPath: /data
      resources:
        requests:
          memory: "64Mi"
          cpu: "256m"
        limits:
          memory: "128Mi"
          cpu: "512m"
    
  volumes:
    - name: persistent-efs-storage
      persistentVolumeClaim:
        claimName: test-pvc
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-2
  namespace: test-ns
spec:
  containers:
    - name: test-2
      image: busybox
      command: ["/bin/sh"]
      args:
        [
          "-c",
          "while true; do echo $(date -u) >> /data/out1.txt; sleep 5; done",
        ]
      volumeMounts:
        - name: persistent-efs-storage
          mountPath: /data
      resources:
        requests:
          memory: "64Mi"
          cpu: "256m"
        limits:
          memory: "128Mi"
          cpu: "512m"
  volumes:
    - name: persistent-efs-storage
      persistentVolumeClaim:
        claimName: test-pvc
